### ISSUE TITLE
"the board" and "the committee" are confusing terms

### ISSUE THREAD

**Issue by bterlson** [tc39/code-of-conduct-proposal#12]
I would say replace "the board" with "the committee" or "TC39", and replace "the committee" with "the CoC enforcement subcommittee" or something?

**Comment by ecmageneva** [comment]
My feeling is that the "Code of Conduct Proposal" is good. It is a general guidelines what is expected from TC39 members while working here. Of course if people want to do some more fine changes on that document that is fine. I would post the final, by TC39 accepted version as guide on the GitHub, make out of it formal TC39 document. 
But as a start I would not operate with a "CoC enforcement subcommittee" or something like that, but on a "self discipline" basis. Start out light and easy.
Nevertheless, both the Ecma Secretariat and the TC39 Management shall be open to any complain and should handle any complain on an individual basis. No special subcommittee, enforcement procedures in force. Use common sense in each case.. So keep the work on the "Enforcement Committee" just in a draft form, and the lighter "self discipline" and common sense in resolution basis does not work, we may go back , pick it up and still introduce it.

**Comment by bterlson** [comment]
@ecmageneva our experience, based on the discussion in plenary, suggests that a CoC without clearly defined enforcement mechanisms are next to useless. Among many other issues, a CoC that says a committee of white dudes will use "common sense" to adjudicate CoC violations will not be taken seriously and is not encouraging for those thinking about reporting issues. As a practical matter we may not "spin up" the subcommittee until a first complaint has been raised, however, in order to keep things light.

So we would like to have a subset of TC39 empowered to make enforcement decisions, which I believe you said was possible under ECMA bylaws. If not, let's work to change them.

**Comment by maggiepint** [comment]
One thing that I have to emphasize is that not everything code of conduct related thing is a violation that has to go to committee. We should be continually asking ourselves "is what I am doing in compliance with the code of conduct?", "Is what I am doing benefiting ECMAScript?", and "Can the point I am making be made without being hurtful?" at all times. In addition, any member of TC39 should feel free to ask those questions of another member of the committee at any time, if they feel that the code of conduct is being violated. This is the best way to avoid a litigation process, and to have health communication in the spirit of the code of conduct.

**Comment by gnarf** [comment]
> No special subcommittee, enforcement procedures in force. Use common sense in each case.

As @bterlson mentioned also, we need clearly defined reporting and enforcement mechanisms.  In the event of any serious infraction, you need reports, you need to know who will read them, and how they should respond, and what sort of enforcement options they are empowered to enact, otherwise the document really doesn't do much to make people feel safer, or like they will be listened to.

> One thing that I have to emphasize is that not everything code of conduct related thing is a violation that has to go to committee.

This is also true, by the nature of having the document, one should feel empowered to hold their peers and themselves accountable to it.  Most "complaints" shouldn't even have a chance to become something a committee needs to hear about. There is still a need for a clearly defined reporting and enforcement procedures when the "talk it out" approach fails.

**Comment by leobalter** [comment]
I'm a +1 to @bterlson suggestions and to establish the enforcement mechanisms by the many reasons already defended in this thread. I'm currently working to fix the current names.
