### ISSUE TITLE
Intro paragraph appears to treat "diversity" as the problem

### ISSUE THREAD

**Issue by ajklein** [tc39/code-of-conduct-proposal#14]
The second sentence reads, "Diversity is one of our goals, but it can also lead to communication issues and unhappiness". This seems to center on "diversity" as the problem, rather than people behaving in a manner that's against the code as the problem.

My initial proposal would be to delete the first part of that sentence and merge it into the one after. This would lead to:

> Like the technical community as a whole, TC39 is made up of a mixture of professionals and volunteers from all over the world. To avoid communication issues and unhappiness, we have a few ground rules that we ask people to adhere to.

Thoughts?

**Comment by leobalter** [comment]
> but it can also lead to communication issues and unhappiness

Reading from this issue, this part feels negative as diversity would lead to unhappiness. 

To not cut out the goal entirely that do you think about adding this small part, to your suggestion:

> Like the technical community as a whole, TC39 is made up of a mixture of professionals and volunteers from all over the world. To avoid communication issues and unhappiness, and to promote inclusiveness, we have a few ground rules that we ask people to adhere to.

**Comment by ajklein** [comment]
@leobalter Your alternative reads well to me and does a good job of introducing the document as well (connecting the goal, inclusiveness, with the code itself).

**Comment by gnarf** [comment]
@leobalter's rewording seems pretty great.
