### ISSUE TITLE
"Be friendly and patient" section gives mixed messages

### ISSUE THREAD

**Issue by ajklein** [tc39/code-of-conduct-proposal#15]
It mostly seems to be about not jumping on people due to different technical backgrounds or understandings, which I'm whole-heartedly in agreement with as a major goal of this effort. But it also includes:

> If someone says something wrong, or says something accidentally offensive, respond with patience and try to keep it polite and civil.

which reads as being about someone, albeit "accidentally", breaking the code. My impression is that this sentence doesn't really belong here, and I feel like the paragraph would be just as effective without it.

**Comment by gnarf** [comment]
Overall I'm :+1: to removing this chunk as well, though it might be nice to find some way to say "if you're offended and decide to let the offender know, please do so in a polite and civil manner"  -- it might not be worth saying though...
