### ISSUE TITLE
Doodle link for the teleconferences regarding the TC39 Code of Conduct Policy.

### ISSUE THREAD

**Issue by ecmageneva** [tc39/code-of-conduct-proposal#27]
Dear All,

Please find below the Doodle link for the teleconferences regarding the TC39 Code of Conduct Policy.

https://ecma-international.doodle.com/poll/2y3pra392ns52fev

As background:

1. The TC39 draft was discussed in the ExeCom in April
2. The ExeCom has prepared a 2nd draft that has been posted over GitHub a few weeks ago
3. That should be discussed in a conf. call (or more conf. calls?) by interested parties, with the goal to come up with a final version that can serve as "TC39 Experimental Code of Conduct Regime" (title something like that....). In that conf call from the ExeCom side Isabelle Valet-Harper who has written the 2nd version would also participate. We expect active participation from the TC39 side too. 

On this doodle we have to agree on the day of the conference call.
But separately we have to agree on what system (like Skype? Hangouts? anything else?) we should have the call (please make suggestions on that)..

Kind regards,
Istvan

Dr. István Sebestyén
Ecma International

**Comment by leobalter** [comment]
see #28
