### ISSUE TITLE
Where this applies

### ISSUE THREAD

**Issue by bakkot** [tc39/code-of-conduct-proposal#3]
Currently this document says

> In addition, violations of this code outside these spaces may affect a person's ability to participate within them.

I think it would be good to be somewhat more specific about where the CoC applies. For example, does it apply when representing TC39 in non-TC39 spaces? (What counts as "representing TC39"?) Does it apply to private political donations? Etc.

I expect there to be gray areas which we don't nail down precisely, but I think we'd be served by being somewhat more specific.

**Comment by michaelficarra** [comment]
I'd go further than @bakkot here; instead of being "somewhat more specific", we should be completely explicit about the locations/events where the CoC applies. Ambiguity can lead to selective/biased enforcement.

**Comment by leobalter** [comment]
I have an idea. This is just a start of this CoC and this topic, as you pointed, is something we need to discuss further. 

Does it work if I remove this paragraph and we limiting it to TC39 meetings and hosted by TC39 based spaces and our [github](https://github.com/tc39) projects?

This way we can discuss the appropriate way to extend this, but I'm not able to specify more than this for now and I agree it's good to tackle specificity.

**Comment by littledan** [comment]
There are some additional TC39-hosted spaces that we should make sure to include: es-discuss and the IRC channels. I think the second sentence of the paragraph does a good job addressing this. If TC39 creates new spaces for people to meet, but we forget to update the CoC, that shouldn't be grounds for lawyering your way out of CoC-related sanctions, I think.

But, besides that, I'm not sure if it's the best thing to be so strictly limited. If I tweet, "#tc39 doesn't want your kind of people because you're \<insert irrelevant superficial characteristic>!!!11", then that should be a code of conduct violation, shouldn't it? Same if I go to the W3C meetings and tell people that in person. And same if I persistently send private emails to another TC39 member saying this kind of thing.

I think the thing to clarify is when one is representing TC39. In those strawman examples I gave, I'd say, even though it's not a TC39-operated forum, a statement like that said by a person others known to be a TC39 member is an act of representing TC39.

I'm not sure what kind of wording we can use to clarify this, though. If we make sure that the enforcement sub-committee consists of people that we can trust as a committee to interpret when people are representing TC39 well, would that help?

**Comment by leobalter** [comment]
I tried to reword the spaces paragraph in Conduct.md clarifying spaces and  outside places (as suggested by @littledan. I'll push the changes soon with a reference to this PR and also for #4.

**Comment by gnarf** [comment]
How about something along the lines of:

> Recent behavior in public spaces will also be considered by the subcommittee.

All forms of public (social media, speaking arrangements, etc) behavior should be a factor considered by the subcommittee.  Someone who has been a hateful ____ist in their twitter timelines should not be welcome to intimidate people (by their presence alone) in spaces managed by TC39.

**Comment by bakkot** [comment]
@gnarf I think covering all public behavior, unconditionally, is somewhat too broad a scope for this CoC.

**Comment by littledan** [comment]
@leobalter This seems like an area of disagreement--whether harassment which doesn't reference TC39 is covered, or whether we only cover things that are actually linked to TC39. I think TC39 should be able to use some sort of sanctions against people who hold their TC39 position over others in conjunction with harassment, but there's some disagreement here about unrelated harassment.

How about wording like this, a bit narrower, but still covering the examples I gave above?

> In addition, the code of conduct applies anywhere a committee member holds up their TC39 participation as a position of authority outside TC39-managed spaces.

It's still a matter of judgement whether a committee member is holding up their participation as a position of authority, but this leaves more distantly related harassment aside.

For comparison, the Chromium code of conduct only applies "to our repos and organizations, mailing lists, blog content, and any other Chromium-supported communication group, as well as any private communication initiated in the context of these spaces.", so I guess it is even narrower. My proposal here is taking a point on the middle of the spectrum.

**Comment by gnarf** [comment]
> leaves more distantly related harassment aside.

Sounds ineffective, would we want to ban Milo from coming to TC39 as an invited guest?

**Comment by gnarf** [comment]
Someone with a known reputation for doxxing trans people, and hate speech, but knows how to "keep their cool" and not be directly harassing in threads on the mailing list should never be allowed near this space.

**Comment by littledan** [comment]
@gnarf Good point; given that, I'm not sure how to address @bakkot 's and @michaelficarra 's point here.

**Comment by leobalter** [comment]
@bakkot 

>  I think covering all public behavior, unconditionally, is somewhat too broad a scope for this CoC.

Remember we'll still have a subcommittee approved by consensus and w/ frequent reviews by TC39 on everything.

@gnarf gave a nice example: someone known for hateful speech in some public spaces capable of being "cool" in other spaces should not really be someone we want to attend the meetings. 

Still, this is something one is not giving a final decision, it needs:

1. review from the subcommittee with an initial decision
2. report to TC39 in a reasonable but limited time
3. review by TC39

We are not defining the subcommittee without consensus. I expect decisions will be reasonable and unfair decisions - if they ever happen - should be reviewed and fixed properly.

Where a decision is applied is certainly within the TC39 managed spaces only, we don't have any government beyond.

Back to the example above, the person with the specific hateful speech may harm our goal for a safe and inclusive space by only their presence in our spaces. We want to protect our spaces and make sure we provide an equal voice and opportunity to everyone, right?

**Comment by ljharb** [comment]
Everyone who isn't interfering with that goal.

**Comment by michaelficarra** [comment]
I would like to get clarification again on the goal of this CoC. My working understanding is that we are trying to guarantee that meeting participants (and es-discuss posters, etc) will be respectful and professional. And with that guarantee, anyone who is planning on also being respectful and professional should feel safe participating. So if someone is *known for being respectful and professional when requested*, why are we trying to prohibit them from participating?

Don't take my comment as anything more than it says on the surface; I'm really just trying to understand what we're trying to accomplish here. Without a clear definition of the goals, we can't know whether we've succeeded or not. And at least I seem to have a different idea of what it is.

**Comment by ljharb** [comment]
To clarify, you mean when someone is unprofessional or disrespectful elsewhere, but responds consistently to requests/policies on professionalism and respectfulness?

**Comment by michaelficarra** [comment]
@ljharb Yes.

**Comment by ljharb** [comment]
I'd say https://github.com/tc39/code-of-conduct-proposal/issues/3#issuecomment-287040113 is a perfect example of why behavior anywhere affects perception everywhere, and why it's a fallacy that the two can be separated.

**Comment by gnarf** [comment]
I've stated my reasons for wanting the committee to consider all of a persons behavior, not just the "civil mask" they wear to a meeting... 

It absolutely makes a difference in how "safe" I would feel coming to a TC39 meeting, and I trust the subcommittee to be reasonable in their decisions about previous behaviors, and scope.

**Comment by littledan** [comment]
@gnarf Thanks for taking the time to explain these issues to me offline.

With this and the committee discussion, I'm now convinced I was wrong and the best thing would be to let the subcommittee take a more broad view to help create a welcoming environment, similar to the original spec text.
