### ISSUE TITLE
Remove changelog?

### ISSUE THREAD

**Issue by littledan** [tc39/code-of-conduct-proposal#31]
The changelog has not been updated yet, even as we have made changes. Should we remove it for now?

**Comment by leobalter** [comment]
I want to say the commits log is fine, but I'd like to ask @gnarf if this fair enough for now before removing it. Otherwise, I'd need to do some homework to organize the changelog file.

**Comment by gnarf** [comment]
Our CoC had the change log for any significant changes because the repo
that housed it served multiple purposes making the commit log less useful

**Comment by leobalter** [comment]
@littledan based on @gnarf's feedback, I would keep the changelog file and use it to track major changes after the initial release.

**Comment by littledan** [comment]
Do we expect our repo here to serve multiple purposes, making the commit log less useful?

**Comment by gnarf** [comment]
yeah i think in this case you could make the changelog a literal link to
the commit log, just make the commits have good descriptions

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by leobalter** [comment]
We might still have commits with structural stuff, like generating html
files.

In anyway, we can give it a shot. If the changelog becomes messy at any
point, we might bring a changelog file back to life.
