### ISSUE TITLE
Clarifications needed

### ISSUE THREAD

**Issue by xjamundx** [tc39/code-of-conduct-proposal#4]
Where do these types of things stand in regard to this document

- political speech, donations, etc
- public twitter account behavior (i.e. members mentions membership in bio, etc)
- private twitter account behavior (i.e. not mentioning TC39 in the description, maybe not obviously connected to the company)

**Comment by gnarf** [comment]
There is more discussion about some of these on #3 as well

**Comment by leobalter** [comment]
I'm applying changes where I try to address this and #3.
